
server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:9596/K?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true

